/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LandingGeneralRouteImport } from './routes/landing-general'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as LoginOperadorRouteImport } from './routes/login_.operador'
import { Route as DashboardOperadorRouteImport } from './routes/dashboard_.operador'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardProductsRouteImport } from './routes/dashboard.products'
import { Route as DashboardPreviewRouteImport } from './routes/dashboard.preview'

const LandingGeneralRoute = LandingGeneralRouteImport.update({
  id: '/landing-general',
  path: '/landing-general',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const LoginOperadorRoute = LoginOperadorRouteImport.update({
  id: '/login_/operador',
  path: '/login/operador',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOperadorRoute = DashboardOperadorRouteImport.update({
  id: '/dashboard_/operador',
  path: '/dashboard/operador',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPreviewRoute = DashboardPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/landing-general': typeof LandingGeneralRoute
  '/dashboard/preview': typeof DashboardPreviewRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/operador': typeof DashboardOperadorRoute
  '/login/operador': typeof LoginOperadorRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/landing-general': typeof LandingGeneralRoute
  '/dashboard/preview': typeof DashboardPreviewRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/operador': typeof DashboardOperadorRoute
  '/login/operador': typeof LoginOperadorRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/landing-general': typeof LandingGeneralRoute
  '/dashboard/preview': typeof DashboardPreviewRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard_/operador': typeof DashboardOperadorRoute
  '/login_/operador': typeof LoginOperadorRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/landing-general'
    | '/dashboard/preview'
    | '/dashboard/products'
    | '/dashboard/profile'
    | '/dashboard/operador'
    | '/login/operador'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/landing-general'
    | '/dashboard/preview'
    | '/dashboard/products'
    | '/dashboard/profile'
    | '/dashboard/operador'
    | '/login/operador'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/login'
    | '/register'
    | '/landing-general'
    | '/dashboard/preview'
    | '/dashboard/products'
    | '/dashboard/profile'
    | '/dashboard_/operador'
    | '/login_/operador'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  LandingGeneralRoute: typeof LandingGeneralRoute
  DashboardOperadorRoute: typeof DashboardOperadorRoute
  LoginOperadorRoute: typeof LoginOperadorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/login_/operador': {
      id: '/login_/operador'
      path: '/login/operador'
      fullPath: '/login/operador'
      preLoaderRoute: typeof LoginOperadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/operador': {
      id: '/dashboard_/operador'
      path: '/dashboard/operador'
      fullPath: '/dashboard/operador'
      preLoaderRoute: typeof DashboardOperadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/preview': {
      id: '/dashboard/preview'
      path: '/preview'
      fullPath: '/dashboard/preview'
      preLoaderRoute: typeof DashboardPreviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/landing-general': {
      id: '/landing-general'
      path: '/landing-general'
      fullPath: '/landing-general'
      preLoaderRoute: typeof LandingGeneralRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardPreviewRoute: typeof DashboardPreviewRoute
  DashboardProductsRoute: typeof DashboardProductsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardPreviewRoute: DashboardPreviewRoute,
  DashboardProductsRoute: DashboardProductsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  LandingGeneralRoute: LandingGeneralRoute,
  DashboardOperadorRoute: DashboardOperadorRoute,
  LoginOperadorRoute: LoginOperadorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
