/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LandingAliadosRouteImport } from './routes/landing-aliados'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as LoginOperadorRouteImport } from './routes/login_.operador'
import { Route as DashboardOperadorRouteImport } from './routes/dashboard_.operador'
import { Route as DashboardRedemptionsRouteImport } from './routes/dashboard.redemptions'
import { Route as DashboardProfileRouteImport } from './routes/dashboard.profile'
import { Route as DashboardProductsRouteImport } from './routes/dashboard.products'
import { Route as DashboardAdsRouteImport } from './routes/dashboard.ads'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingAliadosRoute = LandingAliadosRouteImport.update({
  id: '/landing-aliados',
  path: '/landing-aliados',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const LoginOperadorRoute = LoginOperadorRouteImport.update({
  id: '/login_/operador',
  path: '/login/operador',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOperadorRoute = DashboardOperadorRouteImport.update({
  id: '/dashboard_/operador',
  path: '/dashboard/operador',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRedemptionsRoute = DashboardRedemptionsRouteImport.update({
  id: '/redemptions',
  path: '/redemptions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProductsRoute = DashboardProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdsRoute = DashboardAdsRouteImport.update({
  id: '/ads',
  path: '/ads',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/landing-aliados': typeof LandingAliadosRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/ads': typeof DashboardAdsRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/redemptions': typeof DashboardRedemptionsRoute
  '/dashboard/operador': typeof DashboardOperadorRoute
  '/login/operador': typeof LoginOperadorRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landing-aliados': typeof LandingAliadosRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/ads': typeof DashboardAdsRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/redemptions': typeof DashboardRedemptionsRoute
  '/dashboard/operador': typeof DashboardOperadorRoute
  '/login/operador': typeof LoginOperadorRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/landing-aliados': typeof LandingAliadosRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/dashboard/ads': typeof DashboardAdsRoute
  '/dashboard/products': typeof DashboardProductsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/redemptions': typeof DashboardRedemptionsRoute
  '/dashboard_/operador': typeof DashboardOperadorRoute
  '/login_/operador': typeof LoginOperadorRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/landing-aliados'
    | '/login'
    | '/register'
    | '/dashboard/ads'
    | '/dashboard/products'
    | '/dashboard/profile'
    | '/dashboard/redemptions'
    | '/dashboard/operador'
    | '/login/operador'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/landing-aliados'
    | '/login'
    | '/register'
    | '/dashboard/ads'
    | '/dashboard/products'
    | '/dashboard/profile'
    | '/dashboard/redemptions'
    | '/dashboard/operador'
    | '/login/operador'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/landing-aliados'
    | '/login'
    | '/register'
    | '/dashboard/ads'
    | '/dashboard/products'
    | '/dashboard/profile'
    | '/dashboard/redemptions'
    | '/dashboard_/operador'
    | '/login_/operador'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  LandingAliadosRoute: typeof LandingAliadosRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  DashboardOperadorRoute: typeof DashboardOperadorRoute
  LoginOperadorRoute: typeof LoginOperadorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing-aliados': {
      id: '/landing-aliados'
      path: '/landing-aliados'
      fullPath: '/landing-aliados'
      preLoaderRoute: typeof LandingAliadosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/login_/operador': {
      id: '/login_/operador'
      path: '/login/operador'
      fullPath: '/login/operador'
      preLoaderRoute: typeof LoginOperadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard_/operador': {
      id: '/dashboard_/operador'
      path: '/dashboard/operador'
      fullPath: '/dashboard/operador'
      preLoaderRoute: typeof DashboardOperadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/redemptions': {
      id: '/dashboard/redemptions'
      path: '/redemptions'
      fullPath: '/dashboard/redemptions'
      preLoaderRoute: typeof DashboardRedemptionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/products': {
      id: '/dashboard/products'
      path: '/products'
      fullPath: '/dashboard/products'
      preLoaderRoute: typeof DashboardProductsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ads': {
      id: '/dashboard/ads'
      path: '/ads'
      fullPath: '/dashboard/ads'
      preLoaderRoute: typeof DashboardAdsRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdsRoute: typeof DashboardAdsRoute
  DashboardProductsRoute: typeof DashboardProductsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardRedemptionsRoute: typeof DashboardRedemptionsRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdsRoute: DashboardAdsRoute,
  DashboardProductsRoute: DashboardProductsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardRedemptionsRoute: DashboardRedemptionsRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  LandingAliadosRoute: LandingAliadosRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  DashboardOperadorRoute: DashboardOperadorRoute,
  LoginOperadorRoute: LoginOperadorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
